import {
  Workspace,
  Department,
  Team,
  Role,
  Employee,
  OrganizationChange,
  ActivityLog,
  AIRecommendation,
  HiringPlan,
  Simulation,
} from './types';

// ── Workspace ──────────────────────────────────────────────
export const workspace: Workspace = {
  id: 'ws_northstar',
  name: 'Northstar',
  industry: 'SaaS / B2B',
  size: '45',
  location: 'Mumbai, IN',
  growthStage: 'Series B',
  createdAt: '2022-03-15',
};

// ── Departments ────────────────────────────────────────────
export const departments: Department[] = [
  {
    id: 'dept_eng',
    workspaceId: 'ws_northstar',
    name: 'Engineering',
    description: 'Builds and operates the Northstar platform.',
    headId: 'emp_rk',
    createdAt: '2022-03-15',
  },
  {
    id: 'dept_prod',
    workspaceId: 'ws_northstar',
    name: 'Product',
    description: 'Defines product strategy, roadmap, and user research.',
    headId: 'emp_am',
    createdAt: '2022-03-15',
  },
  {
    id: 'dept_design',
    workspaceId: 'ws_northstar',
    name: 'Design',
    description: 'Owns product design, brand, and design systems.',
    headId: 'emp_sp',
    createdAt: '2022-06-01',
  },
  {
    id: 'dept_sales',
    workspaceId: 'ws_northstar',
    name: 'Sales',
    description: 'Owns pipeline, closing, and account management.',
    headId: 'emp_vs',
    createdAt: '2022-08-01',
  },
  {
    id: 'dept_mktg',
    workspaceId: 'ws_northstar',
    name: 'Marketing',
    description: 'Owns demand generation, content, and brand marketing.',
    headId: 'emp_ns',
    createdAt: '2022-09-15',
  },
  {
    id: 'dept_ops',
    workspaceId: 'ws_northstar',
    name: 'Operations',
    description: 'People ops, finance, and workplace.',
    headId: 'emp_pg',
    createdAt: '2022-03-15',
  },
];

// ── Teams ──────────────────────────────────────────────────
export const teams: Team[] = [
  // Engineering
  {
    id: 'team_frontend',
    departmentId: 'dept_eng',
    name: 'Frontend',
    description: 'Builds and maintains the customer-facing web application.',
    managerId: 'emp_ar',
    responsibilities: [
      'Web application development',
      'Design system implementation',
      'Frontend performance',
      'Customer-facing UI',
    ],
    health: 78,
    createdAt: '2022-03-20',
  },
  {
    id: 'team_backend',
    departmentId: 'dept_eng',
    name: 'Backend',
    description: 'Builds APIs, services, and data infrastructure.',
    managerId: 'emp_rk',
    responsibilities: [
      'API design and development',
      'Service architecture',
      'Database management',
      'Backend reliability',
    ],
    health: 72,
    createdAt: '2022-03-20',
  },
  {
    id: 'team_devops',
    departmentId: 'dept_eng',
    name: 'DevOps',
    description: 'Manages infrastructure, CI/CD, and platform tooling.',
    managerId: 'emp_rk',
    responsibilities: [
      'Infrastructure as code',
      'CI/CD pipelines',
      'Cloud cost management',
      'Deployment automation',
    ],
    health: 68,
    createdAt: '2022-05-01',
  },
  // Product
  {
    id: 'team_product',
    departmentId: 'dept_prod',
    name: 'Product Management',
    description: 'Owns product strategy, roadmap, and squad alignment.',
    managerId: 'emp_am',
    responsibilities: [
      'Product roadmap',
      'Squad prioritization',
      'User research',
      'Stakeholder alignment',
    ],
    health: 65,
    createdAt: '2022-04-01',
  },
  // Design
  {
    id: 'team_design',
    departmentId: 'dept_design',
    name: 'Product Design',
    description: 'Owns UX, UI, prototyping, and design system.',
    managerId: 'emp_sp',
    responsibilities: [
      'Product design',
      'Design system',
      'User research',
      'Prototyping',
    ],
    health: 80,
    createdAt: '2022-06-01',
  },
  // Sales
  {
    id: 'team_sales',
    departmentId: 'dept_sales',
    name: 'Sales',
    description: 'Owns outbound, inbound, and account expansion.',
    managerId: 'emp_vs',
    responsibilities: [
      'Pipeline generation',
      'Deal closing',
      'Account management',
      'Sales operations',
    ],
    health: 75,
    createdAt: '2022-08-01',
  },
  {
    id: 'team_growth',
    departmentId: 'dept_sales',
    name: 'Growth',
    description: 'Owns revenue operations and growth experiments.',
    managerId: 'emp_vs',
    responsibilities: [
      'Growth experiments',
      'Revenue operations',
      'Onboarding optimization',
      'Retention analysis',
    ],
    health: 70,
    createdAt: '2023-01-15',
  },
  // Marketing
  {
    id: 'team_mktg',
    departmentId: 'dept_mktg',
    name: 'Marketing',
    description: 'Owns content, demand gen, and brand.',
    managerId: 'emp_ns',
    responsibilities: [
      'Content marketing',
      'Demand generation',
      'Brand strategy',
      'Event marketing',
    ],
    health: 77,
    createdAt: '2022-09-15',
  },
  // Operations
  {
    id: 'team_ops',
    departmentId: 'dept_ops',
    name: 'Operations',
    description: 'People ops, finance, and workplace experience.',
    managerId: 'emp_pg',
    responsibilities: [
      'People operations',
      'Finance',
      'Workplace management',
      'Vendor management',
    ],
    health: 82,
    createdAt: '2022-03-15',
  },
];

// ── Roles ──────────────────────────────────────────────────
export const roles: Role[] = [
  // Engineering
  {
    id: 'role_cto',
    title: 'CTO',
    departmentId: 'dept_eng',
    teamId: null,
    seniority: 'C_LEVEL',
    responsibilities: ['Engineering strategy', 'Technical leadership', 'Architecture decisions'],
    expectedSkills: ['System design', 'Leadership', 'Strategy'],
  },
  {
    id: 'role_em',
    title: 'Engineering Manager',
    departmentId: 'dept_eng',
    teamId: 'team_frontend',
    seniority: 'MANAGER',
    responsibilities: ['Team management', 'Delivery accountability', 'Hiring', 'Code review'],
    expectedSkills: ['People management', 'Technical leadership', 'Delivery'],
  },
  {
    id: 'role_swe_senior',
    title: 'Senior Software Engineer',
    departmentId: 'dept_eng',
    teamId: 'team_frontend',
    seniority: 'SENIOR',
    responsibilities: ['Feature development', 'Code review', 'Mentoring', 'Architecture'],
    expectedSkills: ['React', 'TypeScript', 'System design'],
  },
  {
    id: 'role_swe',
    title: 'Software Engineer',
    departmentId: 'dept_eng',
    teamId: 'team_backend',
    seniority: 'MID',
    responsibilities: ['Feature development', 'API development', 'Bug fixes', 'Testing'],
    expectedSkills: ['Node.js', 'PostgreSQL', 'API design'],
  },
  {
    id: 'role_swe_junior',
    title: 'Software Engineer I',
    departmentId: 'dept_eng',
    teamId: 'team_backend',
    seniority: 'JUNIOR',
    responsibilities: ['Feature development', 'Bug fixes', 'Testing', 'Documentation'],
    expectedSkills: ['JavaScript', 'SQL', 'Testing'],
  },
  {
    id: 'role_devops',
    title: 'DevOps Engineer',
    departmentId: 'dept_eng',
    teamId: 'team_devops',
    seniority: 'MID',
    responsibilities: ['Infrastructure management', 'CI/CD', 'Monitoring', 'Cost optimization'],
    expectedSkills: ['AWS', 'Terraform', 'Docker', 'Kubernetes'],
  },
  {
    id: 'role_qa',
    title: 'QA Engineer',
    departmentId: 'dept_eng',
    teamId: 'team_frontend',
    seniority: 'MID',
    responsibilities: ['Test automation', 'Quality assurance', 'Bug triage'],
    expectedSkills: ['Cypress', 'Playwright', 'Testing'],
  },
  // Product
  {
    id: 'role_cpo',
    title: 'CPO',
    departmentId: 'dept_prod',
    teamId: null,
    seniority: 'C_LEVEL',
    responsibilities: ['Product vision', 'Roadmap ownership', 'Stakeholder alignment'],
    expectedSkills: ['Product strategy', 'Leadership', 'Market analysis'],
  },
  {
    id: 'role_pm',
    title: 'Product Manager',
    departmentId: 'dept_prod',
    teamId: 'team_product',
    seniority: 'SENIOR',
    responsibilities: ['Roadmap ownership', 'Squad prioritization', 'User research', 'PRDs'],
    expectedSkills: ['Product management', 'Analytics', 'Communication'],
  },
  {
    id: 'role_pm_junior',
    title: 'Associate Product Manager',
    departmentId: 'dept_prod',
    teamId: 'team_product',
    seniority: 'JUNIOR',
    responsibilities: ['Sprint support', 'User research', 'Analytics dashboards'],
    expectedSkills: ['Analytics', 'User research', 'Communication'],
  },
  // Design
  {
    id: 'role_design_head',
    title: 'Head of Design',
    departmentId: 'dept_design',
    teamId: null,
    seniority: 'C_LEVEL',
    responsibilities: ['Design vision', 'Design system ownership', 'Team leadership'],
    expectedSkills: ['Design leadership', 'Figma', 'Design systems'],
  },
  {
    id: 'role_designer',
    title: 'Product Designer',
    departmentId: 'dept_design',
    teamId: 'team_design',
    seniority: 'MID',
    responsibilities: ['Product design', 'Prototyping', 'User research', 'Design system'],
    expectedSkills: ['Figma', 'Prototyping', 'User research'],
  },
  // Sales
  {
    id: 'role_head_sales',
    title: 'Head of Sales',
    departmentId: 'dept_sales',
    teamId: null,
    seniority: 'C_LEVEL',
    responsibilities: ['Sales strategy', 'Pipeline ownership', 'Team management'],
    expectedSkills: ['Sales leadership', 'CRM', 'Negotiation'],
  },
  {
    id: 'role_ae',
    title: 'Account Executive',
    departmentId: 'dept_sales',
    teamId: 'team_sales',
    seniority: 'SENIOR',
    responsibilities: ['Deal closing', 'Pipeline management', 'Account expansion'],
    expectedSkills: ['Sales', 'CRM', 'Negotiation'],
  },
  {
    id: 'role_sdr',
    title: 'Sales Development Rep',
    departmentId: 'dept_sales',
    teamId: 'team_sales',
    seniority: 'JUNIOR',
    responsibilities: ['Outbound prospecting', 'Lead qualification', 'Meeting scheduling'],
    expectedSkills: ['Outbound', 'CRM', 'Communication'],
  },
  {
    id: 'role_growth',
    title: 'Growth Manager',
    departmentId: 'dept_sales',
    teamId: 'team_growth',
    seniority: 'SENIOR',
    responsibilities: ['Growth experiments', 'Revenue operations', 'Retention'],
    expectedSkills: ['Analytics', 'Experimentation', 'SQL'],
  },
  // Marketing
  {
    id: 'role_head_mktg',
    title: 'Head of Marketing',
    departmentId: 'dept_mktg',
    teamId: null,
    seniority: 'C_LEVEL',
    responsibilities: ['Marketing strategy', 'Brand ownership', 'Demand generation'],
    expectedSkills: ['Marketing strategy', 'Content', 'Brand'],
  },
  {
    id: 'role_content',
    title: 'Content Marketer',
    departmentId: 'dept_mktg',
    teamId: 'team_mktg',
    seniority: 'MID',
    responsibilities: ['Content strategy', 'SEO', 'Copywriting', 'Social media'],
    expectedSkills: ['Content', 'SEO', 'Copywriting'],
  },
  // Ops
  {
    id: 'role_head_ops',
    title: 'Head of Operations',
    departmentId: 'dept_ops',
    teamId: null,
    seniority: 'C_LEVEL',
    responsibilities: ['Operations strategy', 'People ops', 'Finance oversight'],
    expectedSkills: ['Operations', 'Finance', 'People ops'],
  },
  {
    id: 'role_hr',
    title: 'People Operations Manager',
    departmentId: 'dept_ops',
    teamId: 'team_ops',
    seniority: 'MANAGER',
    responsibilities: ['Recruitment', 'Onboarding', 'Culture', 'HR policies'],
    expectedSkills: ['People ops', 'Recruitment', 'HR'],
  },
  {
    id: 'role_finance',
    title: 'Finance Manager',
    departmentId: 'dept_ops',
    teamId: 'team_ops',
    seniority: 'MANAGER',
    responsibilities: ['Financial planning', 'Budgeting', 'Payroll', 'Reporting'],
    expectedSkills: ['Finance', 'Accounting', 'Excel'],
  },
];

// ── Employees ──────────────────────────────────────────────
const avatarColors = [
  'hsl(200, 45%, 45%)',
  'hsl(165, 35%, 42%)',
  'hsl(30, 70%, 55%)',
  'hsl(340, 50%, 55%)',
  'hsl(220, 20%, 50%)',
  'hsl(155, 40%, 45%)',
  'hsl(35, 80%, 52%)',
  'hsl(200, 30%, 50%)',
];

function e(
  id: string,
  name: string,
  email: string,
  title: string,
  roleId: string | null,
  departmentId: string,
  teamId: string | null,
  managerId: string | null,
  location: string,
  seniority: Employee['seniority'],
  skills: string[],
  responsibilities: string[],
  joinedAt: string,
  status: Employee['status'] = 'ACTIVE'
): Employee {
  return {
    id,
    workspaceId: 'ws_northstar',
    name,
    email,
    title,
    roleId,
    departmentId,
    teamId,
    managerId,
    location,
    status,
    seniority,
    skills,
    responsibilities,
    avatarColor: avatarColors[Math.floor(Math.random() * avatarColors.length)],
    joinedAt,
  };
}

export const employees: Employee[] = [
  // CEO
  e('emp_ak', 'Ashish Suvarna', 'ashish@northstar.com', 'CEO', null, 'dept_ops', null, null, 'Mumbai', 'C_LEVEL', ['Leadership', 'Strategy', 'Fundraising'], ['Company vision', 'Fundraising', 'Board communication'], '2022-03-01'),

  // Engineering — dept_eng
  e('emp_rk', 'Rahul Khanna', 'rahul@northstar.com', 'CTO', 'role_cto', 'dept_eng', null, 'emp_ak', 'Mumbai', 'C_LEVEL', ['System design', 'Leadership', 'Strategy'], ['Engineering strategy', 'Architecture decisions', 'Hiring'], '2022-03-10'),
  e('emp_ar', 'Aisha Reddy', 'aisha@northstar.com', 'Engineering Manager', 'role_em', 'dept_eng', 'team_frontend', 'emp_rk', 'Bengaluru', 'MANAGER', ['React', 'TypeScript', 'People management'], ['Team management', 'Delivery', 'Code review', 'Hiring'], '2022-04-01'),
  e('emp_jp', 'Jay Patel', 'jay@northstar.com', 'Senior Software Engineer', 'role_swe_senior', 'dept_eng', 'team_frontend', 'emp_ar', 'Bengaluru', 'SENIOR', ['React', 'TypeScript', 'System design'], ['Feature development', 'Code review', 'Mentoring'], '2022-04-15'),
  e('emp_mc', 'Meera Chen', 'meera@northstar.com', 'Senior Software Engineer', 'role_swe_senior', 'dept_eng', 'team_frontend', 'emp_ar', 'Remote', 'SENIOR', ['React', 'GraphQL', 'Performance'], ['Feature development', 'Code review', 'Frontend performance'], '2022-06-01'),
  e('emp_st', 'Sara Thomas', 'sara@northstar.com', 'Software Engineer', 'role_swe', 'dept_eng', 'team_frontend', 'emp_ar', 'Bengaluru', 'MID', ['React', 'TypeScript'], ['Feature development', 'Bug fixes', 'Testing'], '2023-02-01'),
  e('emp_vn', 'Vikram Nair', 'vikram@northstar.com', 'Software Engineer', 'role_swe', 'dept_eng', 'team_frontend', 'emp_ar', 'Remote', 'MID', ['Vue', 'JavaScript'], ['Feature development', 'Bug fixes'], '2023-03-15'),
  e('emp_kb', 'Kabir Bose', 'kabir@northstar.com', 'Software Engineer I', 'role_swe_junior', 'dept_eng', 'team_frontend', 'emp_ar', 'Bengaluru', 'JUNIOR', ['JavaScript', 'React'], ['Feature development', 'Testing', 'Documentation'], '2023-07-01'),
  e('emp_rj', 'Riya Jain', 'riya@northstar.com', 'QA Engineer', 'role_qa', 'dept_eng', 'team_frontend', 'emp_ar', 'Bengaluru', 'MID', ['Cypress', 'Playwright'], ['Test automation', 'Quality assurance', 'Bug triage'], '2022-08-01'),

  // Backend (managed by CTO directly — bottleneck)
  e('emp_ds', 'Dev Sharma', 'dev@northstar.com', 'Senior Software Engineer', 'role_swe_senior', 'dept_eng', 'team_backend', 'emp_rk', 'Mumbai', 'SENIOR', ['Node.js', 'PostgreSQL', 'System design'], ['API development', 'Service architecture', 'Code review'], '2022-04-20'),
  e('emp_at', 'Arjun Thakur', 'arjun@northstar.com', 'Software Engineer', 'role_swe', 'dept_eng', 'team_backend', 'emp_rk', 'Mumbai', 'MID', ['Node.js', 'PostgreSQL'], ['API development', 'Bug fixes', 'Testing'], '2022-07-01'),
  e('emp_pk', 'Priya Kapoor', 'priya@northstar.com', 'Software Engineer', 'role_swe', 'dept_eng', 'team_backend', 'emp_rk', 'Remote', 'MID', ['Python', 'PostgreSQL'], ['API development', 'Data pipelines'], '2022-09-01'),
  e('emp_ng', 'Neha Gupta', 'neha@northstar.com', 'Software Engineer', 'role_swe', 'dept_eng', 'team_backend', 'emp_rk', 'Mumbai', 'MID', ['Node.js', 'Redis'], ['API development', 'Bug fixes'], '2023-01-10'),
  e('emp_rs', 'Rohit Singh', 'rohit@northstar.com', 'Software Engineer I', 'role_swe_junior', 'dept_eng', 'team_backend', 'emp_rk', 'Mumbai', 'JUNIOR', ['JavaScript', 'SQL'], ['Feature development', 'Testing'], '2023-05-01'),
  e('emp_tg', 'Tanvi Gopal', 'tanvi@northstar.com', 'Software Engineer I', 'role_swe_junior', 'dept_eng', 'team_backend', 'emp_rk', 'Remote', 'JUNIOR', ['Python', 'SQL'], ['Feature development', 'Documentation'], '2023-06-15'),

  // DevOps (managed by CTO — overload)
  e('emp_ma', 'Mohan Agarwal', 'mohan@northstar.com', 'DevOps Engineer', 'role_devops', 'dept_eng', 'team_devops', 'emp_rk', 'Mumbai', 'MID', ['AWS', 'Terraform', 'Docker'], ['Infrastructure management', 'CI/CD', 'Monitoring'], '2022-05-15'),
  e('emp_lc', 'Liam Cherian', 'liam@northstar.com', 'DevOps Engineer', 'role_devops', 'dept_eng', 'team_devops', 'emp_rk', 'Bengaluru', 'MID', ['Kubernetes', 'AWS', 'Grafana'], ['Infrastructure management', 'Deployment automation', 'Cost optimization'], '2022-11-01'),

  // Product — dept_prod
  e('emp_am', 'Aditya Mehta', 'aditya@northstar.com', 'CPO', 'role_cpo', 'dept_prod', null, 'emp_ak', 'Mumbai', 'C_LEVEL', ['Product strategy', 'Leadership'], ['Product vision', 'Roadmap ownership', 'Stakeholder alignment'], '2022-03-15'),
  e('emp_sk', 'Sneha Kulkarni', 'sneha@northstar.com', 'Product Manager', 'role_pm', 'dept_prod', 'team_product', 'emp_am', 'Mumbai', 'SENIOR', ['Product management', 'Analytics'], ['Roadmap ownership', 'Squad prioritization', 'PRDs'], '2022-05-01'),
  e('emp_ic', 'Ishaan Choudhury', 'ishaan@northstar.com', 'Product Manager', 'role_pm', 'dept_prod', 'team_product', 'emp_am', 'Bengaluru', 'SENIOR', ['Product management', 'User research'], ['Roadmap ownership', 'User research', 'Stakeholder alignment'], '2022-07-01'),
  e('emp_dv', 'Diya Varghese', 'diya@northstar.com', 'Associate Product Manager', 'role_pm_junior', 'dept_prod', 'team_product', 'emp_sk', 'Mumbai', 'JUNIOR', ['Analytics', 'User research'], ['Sprint support', 'Analytics dashboards', 'User research'], '2023-04-01'),

  // Design — dept_design
  e('emp_sp', 'Sana Pathak', 'sana@northstar.com', 'Head of Design', 'role_design_head', 'dept_design', null, 'emp_ak', 'Mumbai', 'C_LEVEL', ['Design leadership', 'Figma', 'Design systems'], ['Design vision', 'Design system ownership', 'Team leadership'], '2022-06-01'),
  e('emp_kd', 'Karan Desai', 'karan@northstar.com', 'Product Designer', 'role_designer', 'dept_design', 'team_design', 'emp_sp', 'Mumbai', 'MID', ['Figma', 'Prototyping', 'User research'], ['Product design', 'Prototyping', 'Design system'], '2022-08-01'),

  // Sales — dept_sales
  e('emp_vs', 'Vikram Shah', 'vikram.s@northstar.com', 'Head of Sales', 'role_head_sales', 'dept_sales', null, 'emp_ak', 'Mumbai', 'C_LEVEL', ['Sales leadership', 'CRM', 'Negotiation'], ['Sales strategy', 'Pipeline ownership', 'Team management'], '2022-08-01'),
  e('emp_rh', 'Rohini Iyer', 'rohini@northstar.com', 'Account Executive', 'role_ae', 'dept_sales', 'team_sales', 'emp_vs', 'Mumbai', 'SENIOR', ['Sales', 'CRM', 'Negotiation'], ['Deal closing', 'Pipeline management', 'Account expansion'], '2022-09-15'),
  e('emp_fc', 'Farhan Cooper', 'farhan@northstar.com', 'Account Executive', 'role_ae', 'dept_sales', 'team_sales', 'emp_vs', 'Bengaluru', 'SENIOR', ['Sales', 'CRM'], ['Deal closing', 'Pipeline management'], '2022-10-01'),
  e('emp_pn', 'Pooja Nair', 'pooja@northstar.com', 'Sales Development Rep', 'role_sdr', 'dept_sales', 'team_sales', 'emp_rh', 'Mumbai', 'JUNIOR', ['Outbound', 'CRM'], ['Outbound prospecting', 'Lead qualification'], '2023-01-20'),
  e('emp_ob', 'Omar Banerjee', 'omar@northstar.com', 'Sales Development Rep', 'role_sdr', 'dept_sales', 'team_sales', 'emp_rh', 'Mumbai', 'JUNIOR', ['Outbound', 'CRM'], ['Outbound prospecting', 'Meeting scheduling'], '2023-03-01'),
  e('emp_gh', 'Gaurav Hegde', 'gaurav@northstar.com', 'Growth Manager', 'role_growth', 'dept_sales', 'team_growth', 'emp_vs', 'Mumbai', 'SENIOR', ['Analytics', 'Experimentation', 'SQL'], ['Growth experiments', 'Revenue operations', 'Retention analysis'], '2023-01-15'),

  // Marketing — dept_mktg
  e('emp_ns', 'Nisha Saxena', 'nisha@northstar.com', 'Head of Marketing', 'role_head_mktg', 'dept_mktg', null, 'emp_ak', 'Mumbai', 'C_LEVEL', ['Marketing strategy', 'Content', 'Brand'], ['Marketing strategy', 'Brand ownership', 'Demand generation'], '2022-09-15'),
  e('emp_tl', 'Tara Lal', 'tara@northstar.com', 'Content Marketer', 'role_content', 'dept_mktg', 'team_mktg', 'emp_ns', 'Remote', 'MID', ['Content', 'SEO', 'Copywriting'], ['Content strategy', 'SEO', 'Copywriting', 'Social media'], '2022-11-01'),
  e('emp_hd', 'Harsh Dalal', 'harsh@northstar.com', 'Content Marketer', 'role_content', 'dept_mktg', 'team_mktg', 'emp_ns', 'Mumbai', 'MID', ['Content', 'Social media'], ['Content creation', 'Social media management'], '2023-02-15'),

  // Operations — dept_ops
  e('emp_pg', 'Priya Gopal', 'priya.g@northstar.com', 'Head of Operations', 'role_head_ops', 'dept_ops', null, 'emp_ak', 'Mumbai', 'C_LEVEL', ['Operations', 'Finance', 'People ops'], ['Operations strategy', 'People ops', 'Finance oversight'], '2022-03-15'),
  e('emp_js', 'Jaya Srinivasan', 'jaya@northstar.com', 'People Operations Manager', 'role_hr', 'dept_ops', 'team_ops', 'emp_pg', 'Mumbai', 'MANAGER', ['People ops', 'Recruitment', 'HR'], ['Recruitment', 'Onboarding', 'Culture', 'HR policies'], '2022-04-10'),
  e('emp_ek', 'Esha Kapoor', 'esha@northstar.com', 'Finance Manager', 'role_finance', 'dept_ops', 'team_ops', 'emp_pg', 'Mumbai', 'MANAGER', ['Finance', 'Accounting', 'Excel'], ['Financial planning', 'Budgeting', 'Payroll', 'Reporting'], '2022-05-01'),
  e('emp_wq', 'Waseem Quereshi', 'waseem@northstar.com', 'People Operations Manager', 'role_hr', 'dept_ops', 'team_ops', 'emp_js', 'Mumbai', 'MANAGER', ['People ops', 'Recruitment'], ['Recruitment', 'Onboarding', 'Culture'], '2023-01-01'),
  e('emp_zy', 'Zara Yusuf', 'zara@northstar.com', 'Operations Coordinator', null, 'dept_ops', 'team_ops', 'emp_js', 'Mumbai', 'JUNIOR', ['Operations', 'Administration'], ['Workplace management', 'Vendor management', 'Event coordination'], '2023-03-01', 'ON_LEAVE'),
];

// ── Organization changes ──────────────────────────────────
export const orgChanges: OrganizationChange[] = [
  {
    id: 'chg_1',
    type: 'MOVE',
    description: 'Rahul moved from Engineering to Product',
    actorName: 'Priya Gopal',
    affectedEmployeeIds: ['emp_rk'],
    previousState: 'Engineering / Backend Manager',
    newState: 'Product / Strategy Lead',
    timestamp: '2026-08-20T09:30:00Z',
  },
  {
    id: 'chg_2',
    type: 'PROMOTION',
    description: 'Priya became Engineering Manager',
    actorName: 'Ashish Suvarna',
    affectedEmployeeIds: ['emp_pk'],
    previousState: 'Software Engineer',
    newState: 'Engineering Manager',
    timestamp: '2026-08-15T14:00:00Z',
  },
  {
    id: 'chg_3',
    type: 'TEAM_CREATED',
    description: 'Growth department created',
    actorName: 'Vikram Shah',
    affectedEmployeeIds: ['emp_gh'],
    previousState: '—',
    newState: 'Growth / Revenue Operations',
    timestamp: '2026-07-28T10:00:00Z',
  },
  {
    id: 'chg_4',
    type: 'TEAM_MERGED',
    description: 'Marketing team merged with Growth',
    actorName: 'Nisha Saxena',
    affectedEmployeeIds: ['emp_tl', 'emp_hd'],
    previousState: 'Marketing (standalone)',
    newState: 'Marketing + Growth (shared OKRs)',
    timestamp: '2026-07-10T11:30:00Z',
  },
  {
    id: 'chg_5',
    type: 'NEW_HIRE',
    description: 'Tanvi joined as Software Engineer I',
    actorName: 'Jaya Srinivasan',
    affectedEmployeeIds: ['emp_tg'],
    previousState: '—',
    newState: 'Engineering / Backend',
    timestamp: '2026-06-15T09:00:00Z',
  },
  {
    id: 'chg_6',
    type: 'ROLE_CHANGE',
    description: 'Gaurav transitioned to Growth Manager',
    actorName: 'Vikram Shah',
    affectedEmployeeIds: ['emp_gh'],
    previousState: 'Account Executive',
    newState: 'Growth Manager',
    timestamp: '2026-06-01T13:00:00Z',
  },
];

// ── Activity log ──────────────────────────────────────────
export const activityLogs: ActivityLog[] = orgChanges.map((c) => ({
  id: c.id,
  type: c.type,
  description: c.description,
  actor: c.actorName,
  timestamp: c.timestamp,
}));

// ── AI Recommendations ──────────────────────────────────────
export const aiRecommendations: AIRecommendation[] = [
  {
    id: 'rec_1',
    type: 'MANAGEMENT_BOTTLENECK',
    title: 'Engineering management bottleneck',
    description: 'The CTO directly manages 11 people across Backend and DevOps — significantly above the recommended span of 5–7.',
    priority: 'HIGH',
    confidence: 'HIGH',
    affectedTeamIds: ['team_backend', 'team_devops'],
    affectedEmployeeIds: ['emp_ds', 'emp_at', 'emp_pk', 'emp_ng', 'emp_rs', 'emp_tg', 'emp_ma', 'emp_lc'],
    reasoning: 'The CTO currently manages 11 direct reports across two teams. The organizational average is 4.2. A span of 11+ creates a bottleneck for 1:1s, code review, and career growth.',
    supportingData: 'CTO span: 11 | Company average span: 4.2 | Recommended span: 5–7',
    recommendation: 'Promote a Senior Engineer to Engineering Manager for Backend, or split into Platform and Product Engineering.',
    actions: ['Simulate', 'Review', 'Apply'],
    createdAt: '2026-08-22T08:00:00Z',
  },
  {
    id: 'rec_2',
    type: 'RESPONSIBILITY_OVERLAP',
    title: 'Product responsibility overlap',
    description: 'Roadmap ownership is shared between two Product Managers without clear domain boundaries.',
    priority: 'MEDIUM',
    confidence: 'HIGH',
    affectedTeamIds: ['team_product'],
    affectedEmployeeIds: ['emp_sk', 'emp_ic'],
    reasoning: 'Sneha Kulkarni and Ishaan Chouddhury both list "Roadmap ownership" and "Stakeholder alignment" as responsibilities. No domain boundary is defined.',
    supportingData: 'Overlapping responsibilities: 3 | Shared stakeholders: 4 | Unclear ownership areas: 2',
    recommendation: 'Clarify domain ownership: assign Sneha to Growth/Revenue squads and Ishaan to Platform/Eng squads.',
    actions: ['Review', 'Apply'],
    createdAt: '2026-08-21T10:00:00Z',
  },
  {
    id: 'rec_3',
    type: 'STAFFING_GAP',
    title: 'Design capacity is constrained',
    description: '1 Product Designer supports 4 product squads — capacity is below recommended ratio.',
    priority: 'HIGH',
    confidence: 'MEDIUM',
    affectedTeamIds: ['team_design'],
    affectedEmployeeIds: ['emp_kd'],
    reasoning: 'There are 4 product squads but only 1 dedicated product designer. The designer-to-engineer ratio is 1:18, while the industry recommended ratio is 1:8.',
    supportingData: 'Designers: 1 | Squads: 4 | Designer:Engineer ratio: 1:18 | Recommended: 1:8',
    recommendation: 'Hire a Senior Product Designer to support Platform and Growth squads.',
    actions: ['Create hiring plan', 'Review'],
    createdAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'rec_4',
    type: 'STRUCTURE_SIMPLIFICATION',
    title: 'Marketing team structure could be simplified',
    description: 'Two Content Marketers report to the Head of Marketing with overlapping content responsibilities.',
    priority: 'LOW',
    confidence: 'MEDIUM',
    affectedTeamIds: ['team_mktg'],
    affectedEmployeeIds: ['emp_tl', 'emp_hd'],
    reasoning: 'Tara Lal and Harsh Dalal both own content creation and social media. Content ownership is not split by channel or audience.',
    supportingData: 'Overlapping content responsibilities: 2 | No channel ownership defined',
    recommendation: 'Split content ownership: Tara owns long-form + SEO, Harsh owns social + community.',
    actions: ['Review', 'Apply'],
    createdAt: '2026-08-19T09:00:00Z',
  },
];

// ── Hiring plans ───────────────────────────────────────────
export const hiringPlans: HiringPlan[] = [
  {
    id: 'hp_1',
    roleTitle: 'Senior Product Designer',
    departmentId: 'dept_design',
    teamId: 'team_design',
    priority: 'HIGH',
    reason: '4 product squads, 1 existing designer, increased product workload. Current design capacity is constrained.',
    expectedImpact: 'Reduces designer:engineer ratio from 1:18 to 1:9. Unblocks 2 product squads.',
    status: 'OPEN',
    createdAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'hp_2',
    roleTitle: 'Engineering Manager — Backend',
    departmentId: 'dept_eng',
    teamId: 'team_backend',
    priority: 'HIGH',
    reason: 'CTO manages 11 direct reports. Backend team needs a dedicated manager for sustainable growth.',
    expectedImpact: 'Reduces CTO span from 11 to 2. Improves code review velocity and career growth.',
    status: 'OPEN',
    createdAt: '2026-08-22T08:00:00Z',
  },
  {
    id: 'hp_3',
    roleTitle: 'Senior Software Engineer — Platform',
    departmentId: 'dept_eng',
    teamId: 'team_devops',
    priority: 'MEDIUM',
    reason: 'DevOps team has 2 engineers managing all infrastructure. On-call rotation is unsustainable.',
    expectedImpact: 'Enables a healthy 3-person on-call rotation. Improves infrastructure reliability.',
    status: 'OPEN',
    createdAt: '2026-08-18T10:00:00Z',
  },
  {
    id: 'hp_4',
    roleTitle: 'Product Manager — Growth',
    departmentId: 'dept_prod',
    teamId: 'team_product',
    priority: 'MEDIUM',
    reason: 'Growth squad has no dedicated PM. Growth Manager is covering PM responsibilities.',
    expectedImpact: 'Clarifies ownership. Allows Growth Manager to focus on revenue operations.',
    status: 'IN_PROGRESS',
    createdAt: '2026-08-10T09:00:00Z',
  },
];

// ── Simulations ────────────────────────────────────────────
export const simulations: Simulation[] = [
  {
    id: 'sim_1',
    name: 'Split Engineering into Platform and Product Engineering',
    description: 'Move DevOps and Backend infrastructure work under a new Platform Engineering team with a dedicated manager.',
    status: 'ANALYZED',
    changes: [
      {
        type: 'SPLIT_TEAM',
        description: 'Create Platform Engineering team from DevOps + 2 Backend engineers',
        affectedEmployeeIds: ['emp_ma', 'emp_lc', 'emp_ds', 'emp_pk'],
        fromContext: 'Engineering / Backend + DevOps',
        toContext: 'Engineering / Platform Engineering',
      },
      {
        type: 'CHANGE_MANAGER',
        description: 'Promote Dev Sharma to Platform Engineering Manager',
        affectedEmployeeIds: ['emp_ds'],
        fromContext: 'Individual Contributor (Senior SWE)',
        toContext: 'Platform Engineering Manager',
      },
    ],
    createdAt: '2026-08-23T14:00:00Z',
  },
];
